services:
  node1:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    cap_add: [ "NET_RAW", "NET_ADMIN" ]
    networks: [ "l2lab" ]
    volumes:
      - ../../src:/app/src:ro
      - ../../configs:/app/configs:ro
    command: ["sleep","infinity"]   # <— queda vivo

  node2:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    cap_add: [ "NET_RAW", "NET_ADMIN" ]
    networks: [ "l2lab" ]
    volumes:
      - ../../src:/app/src:ro
      - ../../configs:/app/configs:ro
    command: ["sleep","infinity"]   # <— queda vivo

networks:
  l2lab:
    driver: bridge
