services:
  node1:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    command: ["python","-m","l2msg.cli","listen"]
    cap_add: [ "NET_RAW", "NET_ADMIN" ]
    networks: [ "l2lab" ]
    volumes:
      - ../../src:/app/src:ro
      - ../../configs:/app/configs:ro

  node2:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    command: ["python","-m","l2msg.cli","discover"]
    cap_add: [ "NET_RAW", "NET_ADMIN" ]
    networks: [ "l2lab" ]
    volumes:
      - ../../src:/app/src:ro
      - ../../configs:/app/configs:ro

networks:
  l2lab:
    driver: bridge
