[app]
# EtherType experimental reservado para pruebas locales (puedes cambiarlo)
ether_type = "0x88B5"

# "auto" elige la primera interfaz no-loopback (eth0, enp*, etc.)
iface = "auto"

# Nombre para anunciarte en HELLO/ACK
node_name = "nodo-demo"

# Tamaño seguro para payloads iniciales
mtu_safe = 1400

[logging]
level = "INFO"
file  = "logs/l2msg.log"
max_bytes = 5242880
backup_count = 3
console = false

[files]
inbox_dir = "/tmp/l2files"  # si prefieres config en vez de env L2MSG_INBOX